### ISSUE TITLE
Columns first and second params feels it is username / password

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Auth#15]
The `cols` 

``` php
$cols = array(
    'username',
    'password',
    'id',
    'email',
    'fullname',
    'website',
    'twitter'
);

$from = 'users';
$where = 'active = 1';

$pdoadapter = $auth_factory->newPdoAdapter(
    $dbh,
    PASSWORD_BCRYPT,
    $cols,
    $from,
    $where
);
```

assumes the array first and second value is username /  password. That is a wrong assumption . May be we pass an associative array and don't use `$cols[0]` and `$cols[1]` in https://github.com/auraphp/Aura.Auth/blob/421bc6e91ca12881d4d5ccac0905a7805c5b3d5b/src/Adapter/PdoAdapter.php#L96-L105

**Comment by pmjones** [comment]
It's not an assumption; the use passes the column names, so he says exactly what they are.

**Comment by harikt** [comment]
@pmjones not sure what you mean.

**Comment by pmjones** [comment]
I mean, we're not assuming anything. The developer using the package specifies the columns he wants to select; we say the first one has to be the username column, and the second one has to be the password column. Am I missing your point maybe?

**Comment by harikt** [comment]
ok. `$cols` sounds the columns I need to fetch. So basically I just didn't made in the order they were. 

So the order was something like 

``` php
$cols = array(
    'username',
    'email',
    'id',
    'password',
    'fullname',
    'website',
    'twitter'
);
```

and I figured out that the `username` is what it expects to be column 0 and `password` as column 1. What I feel good is is if this is an associative array 

``` php
$cols = array(
    'username' => 'username',
    'email',
    'id',
    'password' => 'password',
    'fullname',
    'website',
    'twitter'
);
```

the order doesn't matters. And we can throw really the exception that username is not present / password not present. 

Else if you look at the first array both the cols[0] and cols[1] are present and we don't get an exception and only saying password incorrect exception. Which I feel is wrong. Docs may fix / mention first column is username and second column is password. But seems good to be associative in my opinion.

Thank you.

**Comment by pmjones** [comment]
This does seem like a doc fix, not a technical issue.

Regarding associative, I was thinkging we want to leave the option for  `"column" => "alias"` in the future.
