### ISSUE TITLE
Timer not cleared on logout (forceLogout)

### ISSUE THREAD

**Issue by enygma** [auraphp/Aura.Auth#2]
Currently, the Timer object passed in isn't cleared (or even reset) as a part of the logout process. I'm happy to update the behavior, but I want to be sure on an approach.

I see the Auth::forceLogout unsetting the other properties (initial, active, etc), does the timer need to be handled the same way? Or would it be beneficial to just call a "reset" on it when the logout happens. It seems like the reset option would allow it to be reused for the anonymous+idle check.

**Comment by harikt** [comment]
Hey @enygma ,
I had a look into the problem. It took sometime to see whether `refresh` ( https://github.com/auraphp/Aura.Auth/blob/7a31a1ecad3b479968309b3d87e3d31fd4c06c24/src/Auth.php#L111 ) .

Update : This is already covered here https://github.com/auraphp/Aura.Auth/blob/abb26e4a17feee3c61ef98da94a7d03c055b5ae6/tests/src/AuthTest.php#L29

**Comment by pmjones** [comment]
I think this has been obviated by later development. At logout time, the first and last active times are cleared now. Please let me know if this continues to be a problem,
