### ISSUE TITLE
Intent of session instance in Auth class?

### ISSUE THREAD

**Issue by enygma** [auraphp/Aura.Auth#3]
I see that the SessionDataInterface instance passed in to the Auth class is used to store user information, but it's definitely possible that there's more context in the current session than just the user information (permissions, roles, etc). Is the goal of the session handling in this case to track that other information? If so, does the Auth class need to be flexible enough to pull that information from the session? 

Maybe thinking some kind of repository or collection where data could be pulled with a "get_" method where the "_" is the property name...thoughts?

**Comment by harikt** [comment]
You are right, in pdo we can store the additional information. See the columns that are passed https://github.com/auraphp/Aura.Auth#pdo-adapter ( so I assume the roles and permission can also be stored )

**Comment by pmjones** [comment]
The session _segment_ (i.e., `$_SESSION['Aura\Auth\Auth'][...]`) is intended to track only the auth info (username and password). Other packages may use other segments to track their own information.

The session _manager_ is intended to handle start/stop/etc activities.

There is no session save handler provided; I think those are more the responsibility of a separate layer.
