### ISSUE TITLE
PDO: Thrown exception error messages

### ISSUE THREAD

**Issue by quasipickle** [auraphp/Aura.Auth#52]
Is there a reason no error messages are include with thrown exceptions (ie: "Exception\PasswordIncorrect" or "Exception\UsernameNotFound"?  Is it an i18n concern?

**Comment by harikt** [comment]
I assume the user can catch the exception and do add the needful messages via Aura.Intl or add to Aura.Filter or some other way.

**Comment by pmjones** [comment]
It is partially an I18N issue, yes. The idea is that the package should only throw the exception, and the end-user (developer) can do whatever is needed with the exception.

Hope that makes sense.

**Comment by quasipickle** [comment]
Adding a message doesn't stop the developer from doing anything at all with the exception.  What it does do though, is prevent a generic catch-all exception catch.  Rather than just output the message, I have to catch every possible type of exception, then act accordingly.

It's certainly not the end of the world, but I think it does affect the usability of the library.

**Comment by harikt** [comment]
@quasipickle if I understand you, 

You are looking to add some message on throwing an exception?

``` php
throw new Exception\PasswordIncorrect('Password is incorrect.');
```

that way you can use 

``` php
try {
    // auth stuffs
} catch (Exception $e) {
    echo $e->getMessage();
}
```

I don't have any trouble to add a generic message, send a PR if you like or ask Paul if this is what you are looking for.

Thanks

**Comment by harikt** [comment]
ask Paul in the sense before you send the PR whether he likes the approach or not.

**Comment by quasipickle** [comment]
@harikt You understand correctly.
@pmjones How does this sound?
