### ISSUE TITLE
Auth object calling session_start

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Auth#61]
Hi Paul, 

I am wondering why not we can implement the `Aura\Auth\Auth` can call the `session_start` on any call to `Auth` methods rather than using a service like Resume and asking to start manually by users ?

Also most of the adapters are not having a logout method and in the wake of it may be we should think of having accepting the adapter being null also.

So users don't need to create the adapter objects ( especially something like PDO ) and pass to it.

Thanks!

**Comment by pmjones** [comment]
>  why not we can implement the Aura\Auth\Auth can call the session_start on any call to Auth

Because then we would need to inject to services into the Auth object, and have it figure out when to call those services.

> most of the adapters are not having a logout method

Most of the storage adapters don't need it, as they don't need to store the fact that the user has logged out.
