### ISSUE TITLE
Rehash

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Auth#62]
Hi Paul, 

It seems that it will be good to update the password making use of http://php.net/manual/en/function.password-needs-rehash.php . 

Else the problem is developers probably will never make use of rehashing and will forget about it.

For the sake of good to happen I feel it is good to make use of the rehashing at the library level .

Thanks

**Comment by dshafik** [comment]
[More info here](https://github.com/dshafik/securepasswords.info/pull/15#issuecomment-68488836)

**Comment by pmjones** [comment]
If we do the rehash, then we have to store the rehash. That gets us into the business of writing to different account storage systems, which I'd prefer to avoid. It's one thing to _read_ from IMAP, LDAP, the file system, and SQL; it's another thing entirely to write back to them in a safe way.

Instead, implementors can write an adapter that checks the hash, rehashes it as needed, and then stores the modified hash, according to their account storage constraints.
