### ISSUE TITLE
Does HtpasswordVerifier need to verify the password hash is buggy and using bcrypt ?

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Auth#63]
I was going through the post https://blog.engineyard.com/2014/password-security-part-3 and it was mentioning about 
- $2a$ — Potentially buggy
- $2x$ — Known buggy hash
- $2y$ — Using the corrected version

So I am wondering whether we need any change for   https://github.com/auraphp/Aura.Auth/blob/1468cc76fdba299554cc4d5c2bd164d747f17a63/src/Verifier/HtpasswdVerifier.php#L44

``` php
$str = substr($hashvalue, 0, 4);
if ($str == '$2y$' || $str == '$2a$' || $str == '$2x$') {
    return password_verify($plaintext, $hashvalue);
}
```

**Comment by pmjones** [comment]
Since the $2a$ and $2x$ are buggy, it seems best _not_ to honor them.
