### ISSUE TITLE
Can't use minimum-stability: stable with this package

### ISSUE THREAD

**Issue by brandonsavage** [auraphp/Aura.Auth#71]
This package hasn't been significantly modified since well before August, and yet it's still in beta. This prevents using minimum-stability: stable in Composer. When is this package expected to be released?

**Comment by pmjones** [comment]
Please review the 2.0 release as of about a minute ago, and let me know if that solves this issue for you. :-)

**Comment by brandonsavage** [comment]
Resolved!
