### ISSUE TITLE
Probably good to have messages passed for Exceptions ?

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Auth#73]
Hi, 

It looks good to me to pass messages when throwing exceptions.

Eg : `throw new UsernameMissing("Username is missing");` .

Reason I was using try catch and it was hard to debug what the exception have caught until I recognized the message was missing ?

What do you think of adding message when throwing exceptions ?

**Comment by harikt** [comment]
I am happy to send a PR if everyone agrees.

**Comment by brandonsavage** [comment]
The exception type itself should be sufficient, no?

**Comment by harikt** [comment]
I am looking at a case 

``` php
try {
    doSomething();
} catch (Exception $e) {
    $this->log($e->getMessage());
}
```

You may argue that you can get the object class via `get_class($e)` , but most of the time people expect a message also.
