### ISSUE TITLE
LdapAdapter::bind performs a double unbind on the underlying ldap resource

### ISSUE THREAD

**Issue by erikjwaxx** [auraphp/Aura.Auth#74]
Per the [PHP docs](http://php.net/manual/en/function.ldap-close.php) `ldap_close` is an alias for `ldap_unbind`. But, when calling `LdapAdapter::bind`, after the bind succeeds both `ldap_unbind` and `ldap_close` are called on the LDAP resource, which emits a PHP error when attempting to close the (now-closed) resource the second time.

**Comment by erikjwaxx** [comment]
https://github.com/auraphp/Aura.Auth/pull/75 is opened to rectify this

**Comment by harikt** [comment]
Closing for you have provided the fix in #75 . Thank you.
