### ISSUE TITLE
Default timeout values

### ISSUE THREAD

**Issue by cxj** [auraphp/Aura.Auth#81]
I think we should update and better document the various default timeout values, presently set to zero, 1440 and 14400 (forever, 24 minutes and 4 hours respectively).  They're kind of cryptic and probably are not really good defaults, anyway.

The 1440 value comes from the original PHP 4 sessions, back when the value was minutes, not seconds.  1440 is one entire day in minutes (24 times 60).

I'll be happy to make a pull request for the changes.  Just wanted to start a bit of discussion on what good default values might be.

**Comment by cxj** [comment]
I note that some values must be less than or equal to other values, among the various time to live timeouts (or inversely, some values must be larger than others).  It would be good to include that "hierarchy" of values in the documentation, as well, so developers using this package don't have to hunt through the code to find all the various checks against those kinds of things.

**Comment by cxj** [comment]
Code fixed by 8eae3f140af171a49dd9828cdfecfa5e6b4975a0.  Improved documentation on actual meaning or hierarchy of timeouts To Be Done.

**Comment by harikt** [comment]
Thank you. Closing this as it is fixed with #84 .
