### ISSUE TITLE
Missing return values, or changed API and docblock out of date?

### ISSUE THREAD

**Issue by cxj** [auraphp/Aura.Auth#83]
The code [here](https://github.com/auraphp/Aura.Auth/blob/2.x/src/Service/ResumeService.php#L94) at `ResumeService::resume()` says the method returns a boolean indicating whether the session still exists.  But the method does not return a value at all.

Should the docblock be updated to not mention a return value, or should the code be corrected to actually return the documented value?

**Comment by pmjones** [comment]
Good eyes. Change the docblock to "returns null."

**Comment by cxj** [comment]
Will do.  PR momentarily.

**Comment by harikt** [comment]
PR : https://github.com/auraphp/Aura.Auth/pull/85

**Comment by harikt** [comment]
closing in favour of #87 being merged.
