### ISSUE TITLE
New release builds, please?

### ISSUE THREAD

**Issue by cxj** [auraphp/Aura.Auth#97]
Could we get some up to date releases tagged?  I've been using 2.x-dev for a long time.  ;-)

**Comment by harikt** [comment]
Sorry I have not seen this message. I can look into this in the coming days and do a release. Anything I need to take special attention to ?

PS : In case I miss again, please ping me.

**Comment by cxj** [comment]
Nothing special.  Just having a tag I can use in my `composer.json` file for releases would be very helpful.

**Comment by harikt** [comment]
ok, I will do it tomorrow early morning.

**Comment by harikt** [comment]
Hi @cxj ,

I looked into this, and noticed my comment on https://github.com/auraphp/Aura.Auth/pull/84#issuecomment-312483846 . The default `session.gc_maxlifetime => 1440 => 1440` . And the PR #84 already made the change. As it is config for Aura framework, that may not have broken users. But the PR #89 will. 

What I would suggest is to override the values passed to Timer https://github.com/auraphp/Aura.Auth/blob/955ef972b5f0f67e855f4f82ce6752f99e665270/config/Common.php#L101-L106 with your own. That will actually fix your problem.

For the current time I don't think I can make a release and I believe the patch #84 need to be reverted.

**Comment by cxj** [comment]
I have already changed the values in _my_ copy of `Aura.Auth/config/Common.php` to suit my needs.  PR #84 and PR #89 were designed to change the default value used by `Aura.Auth` to be a sane, intelligent value for all future users of `Aura.Auth`.  

The default value used by `Travis` of 1440, and in the PHP releases of the `php.ini` file with `session.gc_maxlifetime = 1440` are **erroneous**.  See https://stackoverflow.com/questions/14703363/why-is-the-standard-session-lifetime-24-minutes-1440-seconds/37176824#37176824 for the full explanation.

**Comment by harikt** [comment]
@cxj I agree with you, but I think it is up to the users to modify his / her `session.gc_maxlifetime` . If someone in the @auraphp/docs-team can give a green card. I will do. For me it looks not good.

**Comment by Qrzysio** [comment]
I agree it's up to users how long `session.gc_maxlifetime` should be. It's quite annoying now to deal with this low limit. I would really appreciate to see a new release which fixed this issue.

**Comment by harikt** [comment]
> I agree it's up to users how long session.gc_maxlifetime should be. It's
> quite annoying now to deal with this low limit.
>
Why not override the default config.

> I would really appreciate to see a new release which fixed this issue.
>
I will look what I can do.

**Comment by Qrzysio** [comment]
Well, I didn't want to touch the source, so in case of an update, I do not lose my "fixes". I didn't expect there will be no updates at all for a long time ;).

Anyway, I've tried hard to manage the behaviour of how long the sessions are and how to manipulate the timer. Probably my knowledge is not good enough to get it, or the script itself does not allow to extend the time of being logged in.

```
@ini_set("session.gc_maxlifetime", 3600*24);
@ini_set("session.cookie_lifetime", 3600*24);

$aura = new \Aura\Auth\Session\Timer(3600*48, 3600*24, 0, 0);
$aura->setIdleTtl(7200);
$aura->setExpireTtl(3600*24);
```

**Comment by harikt** [comment]
You don't want to change source. You can add another config . Ie what I
meant by override. I think I have commented about it on this thread. So you
don't want to rely on the changes happening on config of package.

**Comment by harikt** [comment]
Hi @cxj , 

I have added you as a maintainer. I hope @pmjones will also agree without any hesitation .

Keep things moving forward. I will be around in case if you need any help.

**Comment by pmjones** [comment]
Oh, I thought he already had been added. Thanks @harikt !

**Comment by harikt** [comment]
@pmjones I have added him to Aura.Auth for now. I don't see a way to add him to the team. Oh and you are fast to reply :+1:  .

**Comment by cxj** [comment]
Obviated by having a 4.x branch with the needed changes.
